enabled: true
namespace: openshift-operators
name: openshift-pipelines-operator
subscription:
  channel: latest
  approval: Automatic
  operatorName: openshift-pipelines-operator-rh
  sourceName: redhat-operators
  sourceNamespace: openshift-marketplace
operatorgroup:
  create: false