apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhacs-operator.rhacs-operator: ""
  name: {{ .Values.name }} 
  namespace: {{ .Values.namespace }}  
spec:
  channel: {{ .Values.subscription.channel }} 
  installPlanApproval: {{ .Values.subscription.approval }}
  name: {{ .Values.name }}
  source: {{ .Values.subscription.source }} 
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  {{- if .Values.subscription.csv }}
  startingCSV: {{ .Values.subscription.csv }}
  {{- end }}