{{ if eq (.Values.enabled | toString) "true" }}
{{- if .Values.operatorgroup.create }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.name | default "devops-operator-group" | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  targetNamespaces:
  - {{ .Values.namespace }}
{{- end }}
{{- end }}

