enabled: true
namespace: rhacs-operator
name: rhacs-operator 
subscription:
  channel: stable
  approval: manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
operatorgroup:
  create: false